// This file was generated by prisma-field-encryption.

import type { PrismaClient, accounts } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = accounts['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'accounts',
    client,
    getTotalCount: client.accounts.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.accounts.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        name: true,
        starting_balance: true,
        notes: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.accounts.update({
      where: {
        id: record.id
      },
      data: {
        name: record.name,
        starting_balance: record.starting_balance,
        notes: record.notes
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "name": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "starting_balance": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "notes": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "vault": {
 *       "modelName": "vaults",
 *       "isList": false
 *     },
 *     "member": {
 *       "modelName": "members",
 *       "isList": false
 *     },
 *     "expenses": {
 *       "modelName": "expenses",
 *       "isList": true
 *     },
 *     "income": {
 *       "modelName": "income",
 *       "isList": true
 *     },
 *     "subscriptions": {
 *       "modelName": "subscriptions",
 *       "isList": true
 *     },
 *     "investments": {
 *       "modelName": "investments",
 *       "isList": true
 *     }
 *   }
 * }
 */
