// This file was generated by prisma-field-encryption.

import type { PrismaClient, tax_pnl_holdings } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = tax_pnl_holdings['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'tax_pnl_holdings',
    client,
    getTotalCount: client.tax_pnl_holdings.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.tax_pnl_holdings.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        symbol: true,
        quantity: true,
        quantity_long_term: true,
        average_price: true,
        current_price: true,
        pnl: true,
        pnl_percentage: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.tax_pnl_holdings.update({
      where: {
        id: record.id
      },
      data: {
        symbol: record.symbol,
        quantity: record.quantity,
        quantity_long_term: record.quantity_long_term,
        average_price: record.average_price,
        current_price: record.current_price,
        pnl: record.pnl,
        pnl_percentage: record.pnl_percentage
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "symbol": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "quantity": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "quantity_long_term": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "average_price": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "current_price": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "pnl": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "pnl_percentage": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "upload": {
 *       "modelName": "tax_pnl_uploads",
 *       "isList": false
 *     }
 *   }
 * }
 */
